remove_quick_mode:

remove_holiday_mode:

set_quick_mode:
  fields:
    quick_mode:
      example: QM_HOTWATER_BOOST, QM_VENTILATION_BOOST, QM_ONE_DAY_AWAY, QM_SYSTEM_OFF, QM_ONE_DAY_AT_HOME, QM_PARTY
      selector:
        select:
          options:
            - QM_HOTWATER_BOOST
            - QM_VENTILATION_BOOST
            - QM_ONE_DAY_AWAY
            - QM_SYSTEM_OFF
            - QM_ONE_DAY_AT_HOME
            - QM_PARTY
    duration:
      example: 3
      selector:
        number:
          min: 0
          max: 7
          mode: box

set_holiday_mode:
  fields:
    start_date:
      example: "2019-11-25"
      selector:
        date:
    end_date:
      example: "2019-11-26"
      selector:
        date:
    temperature:
      example: 15
      selector:
        number:
          min: 5
          max: 30
          mode: box

set_quick_veto:
  fields:
    entity_id:
      example: climate.bathroom
      selector:
        entity:
          integration: multimatic
          domain: climate
    temperature:
      example: 25
      selector:
        number:
          min: 5
          max: 30
          mode: box
    duration:
      example: 60
      selector:
        number:
          min: 30
          max: 1440
          mode: box

remove_quick_veto:
  fields:
    entity_id:
      example: climate.bathroom
      selector:
        entity:
          integration: multimatic
          domain: climate

request_hvac_update:

set_ventilation_day_level:
  fields:
    entity_id:
      example: fan.bathroom
      selector:
        entity:
          integration: multimatic
          domain: fan
    level:
      example: 1
      selector:
        number:
          min: 1
          max: 7
          mode: box

set_ventilation_night_level:
  fields:
    entity_id:
      example: fan.bathroom
      selector:
        entity:
          integration: multimatic
          domain: fan
    level:
      example: 2
      selector:
        number:
          min: 1
          max: 7
          mode: box

set_datetime:
  fields:
    datetime:
      example: 2022-11-06T11:11:38
      selector:
        datetime:
